spring:
  application:
    name: biblioteca

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:biblioteca}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: biblioteca-pool
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
